// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package common

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for DIDMethod.
const (
	DIDMethodKey DIDMethod = "key"
	DIDMethodOrb DIDMethod = "orb"
	DIDMethodWeb DIDMethod = "web"
)

// Defines values for KMSConfigType.
const (
	KMSConfigTypeAws   KMSConfigType = "aws"
	KMSConfigTypeLocal KMSConfigType = "local"
	KMSConfigTypeWeb   KMSConfigType = "web"
)

// Defines values for VCFormat.
const (
	CwtVcLd     VCFormat = "cwt_vc-ld"
	JwtVcJson   VCFormat = "jwt_vc_json"
	JwtVcJsonLd VCFormat = "jwt_vc_json-ld"
	LdpVc       VCFormat = "ldp_vc"
	MsoMdoc     VCFormat = "mso_mdoc"
	VcSdJwt     VCFormat = "vc+sd-jwt"
)

// Defines values for VPFormat.
const (
	CwtVp VPFormat = "cwt_vp"
	JwtVp VPFormat = "jwt_vp"
	LdpVp VPFormat = "ldp_vp"
)

// Model to convey the details about the Credentials the Client wants to obtain.
type AuthorizationDetails struct {
	// REQUIRED when Format parameter is not present. String specifying a unique identifier of the Credential being described in the credential_configurations_supported map in the Credential Issuer Metadata. The referenced object in the credential_configurations_supported map conveys the details, such as the format, for issuance of the requested Credential. It MUST NOT be present if format parameter is present.
	CredentialConfigurationId *string `json:"credential_configuration_id,omitempty"`

	// Object containing the detailed description of the credential type.
	CredentialDefinition *CredentialDefinition `json:"credential_definition,omitempty"`

	// For Token response only. Array of strings, each uniquely identifying a Credential that can be issued using the Access Token returned in this response. Each of these Credentials corresponds to the same entry in the credential_configurations_supported Credential Issuer metadata but can contain different claim values or a different subset of claims within the claims set identified by that Credential type.
	CredentialIdentifiers *[]string `json:"credential_identifiers,omitempty"`

	// REQUIRED when CredentialConfigurationId parameter is not present. String identifying the format of the Credential the Wallet needs. This Credential format identifier determines further claims in the authorization details object needed to identify the Credential type in the requested format. It MUST NOT be present if credential_configuration_id parameter is present.
	Format *string `json:"format,omitempty"`

	// An array of strings that allows a client to specify the location of the resource server(s) allowing the Authorization Server to mint audience restricted access tokens.
	Locations *[]string `json:"locations,omitempty"`

	// String that determines the authorization details type. MUST be set to "openid_credential" for OIDC4VC.
	Type string `json:"type"`
}

// Object containing the detailed description of the credential type.
type CredentialDefinition struct {
	// For ldp_vc only. Array as defined in https://www.w3.org/TR/vc-data-model/#contexts.
	Context *[]string `json:"@context,omitempty"`

	// An object containing a list of name/value pairs, where each name identifies a claim offered in the Credential. The value can be another such object (nested data structures), or an array of such objects.
	CredentialSubject *map[string]interface{} `json:"credentialSubject,omitempty"`

	// Array designating the types a certain credential type supports
	Type []string `json:"type"`
}

// DID method of the DID to be used for signing.
type DIDMethod string

// Model for KMS configuration.
type KMSConfig struct {
	// Prefix of database used by local kms.
	DbPrefix *string `json:"dbPrefix,omitempty"`

	// Type of database used by local kms.
	DbType *string `json:"dbType,omitempty"`

	// URL to database used by local kms.
	DbURL *string `json:"dbURL,omitempty"`

	// KMS endpoint.
	Endpoint *string `json:"endpoint,omitempty"`

	// Path to secret lock used by local kms.
	SecretLockKeyPath *string `json:"secretLockKeyPath,omitempty"`

	// Type of kms used to create and store DID keys.
	Type KMSConfigType `json:"type"`
}

// Type of kms used to create and store DID keys.
type KMSConfigType string

// Supported VC formats.
type VCFormat string

// Supported VP formats.
type VPFormat string

// WalletInitiatedFlowData defines model for WalletInitiatedFlowData.
type WalletInitiatedFlowData struct {
	ClaimEndpoint        string    `json:"claim_endpoint"`
	CredentialTemplateId string    `json:"credential_template_id"`
	OpState              string    `json:"op_state"`
	ProfileId            string    `json:"profile_id"`
	ProfileVersion       string    `json:"profile_version"`
	Scopes               *[]string `json:"scopes"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/5xXTXPbOBL9K12YPSS1tJTazEmn9UpOlSrxxGs5msPOlAoCWiZiEuAATSnaVP77VgOk",
	"RImUHe/FFvHReOh+/brxXShXVs6ipSAm30VQOZYy/ryuKXfe/FeScXaGJE0RxzUG5U3Fo2Iibp3GAsiB",
	"cnaLe6AcQafFINeupjgy9ajRkpFFSN+FQUuwk5YCb3ZrksaORCYq7yr0ZDCepQ77VsrZjXmsfYSzMroP",
	"5f7m31/m9zcz2OVo4YPzpSSopJclEnowAawjqDwGtDSCBXljHyFUqMxmzz8l1Nb8VSOYeOjGoAe3ObsA",
	"rJHXpqPXqMHYuOIS1LAKdVU5T6ihlFW7vGNwHkKNHm6RpJYkR/CQI3jcoEerUINbf0VFrz0nxSN0A5JB",
	"qFUOMg1uooMy/g8mhFpahe11Pf5VY2BTR5wjmBPcflk8wG+fH2CNrSfBbBpbp85uHS0yQfsKxUSE6HHx",
	"I+vGVePGWJNC+F38zeNGTMQv4yMtxw0nx0cos+OeU2PHwA1Q9YPz8OCe0ILHUDkbEJwt9iO49l7u+eoJ",
	"YMgApcobMhT7lg4NRzqRo1wSKGnZG+xC1FAHXsU+vFYKQzicSLW3LVtMOEAYwQ2flfweTjNFOZ+W6Zgk",
	"bDTIEgEt+f1r+NAnW9mQDdZ1uoFyllMQtNlE4hGoQpoStrKoMYDzIDtzoV4HJEYdVwXYGcpbQGmE5w/h",
	"0LDeJ291vbevkNlhCMsYrh5NmgHJ8eHvRLOXMv94xLTrkLl+WQy6kT7myIAI8OfvsiiQwCLqwElrQndF",
	"s7UjJZpPLo3FAJvaU46+9VXjOdlV3IOKNunPx6BmHrQge5j2FbamjgmccDyXvM+I7M9ndOFUol0/OtcW",
	"5FmGJS7IonC7ABJUKgfkWjWOd2hNHkUpuNorhIB+i/5NeJssHBLuxH2LuIhtlsYSyFobllO2Qt4odo1M",
	"GUqcoeF1TEzf5zdtWBQv14n25djGFEhxWWNMGXLwh3AVWqNXx8D8IaJMf57Ppr8upwMB+JEJDrnxqMXk",
	"P2n2z0yQoYKXDdbyg5HEML7WoMT2rvk5MbKRjNb96U6oobO4DZ3qZ/1pof8nG8NvNKzaha5WW3Wi1jJA",
	"rBxJUnOiKkzG491uN9q9Hzn/OH64H2/VFWvcVck9yviX5ohXRvoIfVEnPw0R3PVcIqEwIUqHlSWOo45C",
	"JY0PGcuUx1RkePIoEikZWHddlFrdbxdSe5DMNaVHWhfVJFb3Bskbm9I/inwgXyuqPYa3WZTybkYeN4XR",
	"ECeGqZ6ioDGYRyup5QCvjXdAH6vJWdyhKUnhFRF4gdlDjG19cGwtBi82m89ukXI30ErO5jMukbnTLYN5",
	"hBx7uw5JVYGvbuwj20Zbl4zO+bXIxA757xPuI9Dz6328XaS6dKmZZtsfbxdwIsb9lNHrO48b861vJo0z",
	"co7+WoYG9HofNbWApzIMirhePwwGm0f/L3Nf7j/1rX25/8SufKUxtLpyxg6kH/uqnR3cGlB5pE9OPX3E",
	"/Z2kfMBlkvJYf+JShvL0k7joWY89lSHZ4ReSR0mcrRoCOZ849YT70GVQPOzAIbkLAxx6ISWOBDsnfSa+",
	"XZF8DLwr9qte/PkjE8vphwuN1eLQQi6nTSdxgvbrjlZbtfoanL0qtMiEigPpd2dSZCJpuMjEVv096Kuv",
	"O4ZTBrcqtVNd+Ac0A85e3v0E0ruLSKsWR9VCrU5Ovrt8cmr25iwnklB/KNxuJkkyEFsXhVyzBfI19p6w",
	"LOerLnufew0RllUhCZsHbm+pq1aBJOHgZOXdxhQX97bTW/Shqev9VFGuSrgv6/P5fZ/V6w6mPoLDedm5",
	"my46peOCTuQuRaen+gzP2I0byFhfB/pX4RQsp4u2UHUL2OGNzAm8RW82pulP05vv9/dTWE6vru/mIAtn",
	"H+ObCD5XaOezX5dTqLwjp1xxeHCjH0cz3FxbQi9VtBa3pQsxgQuj0IYYcO4VuPRWUuV49Y/RO5GJ2hdi",
	"Irr9j4zTsQdq9obxp/n05rfFDe8Z0bdU1tsC6srS2aZyM7RlvBoHuPu44HbaKIQ3y+niLWdxSyLxbsRI",
	"IjfRysqIiXg/ehfBVZLyICZMmB//CwAA//8nzHj8ahIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
